name: Node Github CI/CD

on:
  push:
    branches:
      - develop

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]    
    steps: 
      - uses: actions/checkout@v2
      - name: use Node.js ${{ matrix.node-version }}
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
        name: yarn install and test
        run: 
          yarn install
          yarn test
        env:
         CI: true
  
 deploy:
   runs-on: ubuntu-latest

   steps:
     - uses: actions/checkout@v2
     - run: docker build -t nonsookongwu/todo
     - run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u s {{secrets.DOCKER_USERNAME}} --password-stdin
     - run: docker push nonsookongwu/todo
  